### ISSUE TITLE
[SQLSTATE[42S02] Error When Using filament-backup Package]: 

### ISSUE THREAD

**Issue by anastalal** [oriondevelops/filament-backup#1]
### What happened?

I am encountering an issue when trying to create a backup using the "filament-backup" package. The error message I'm receiving is: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database_Name.queue_monitors' doesn't exist.

### How to reproduce the bug

1. Install and configure the "filament-backup" package in a Laravel project.
2. Attempt to create a backup using the provided functionality.
3. Observe the error message mentioned above.

### Package Version

1.0

### PHP Version

8.1.17

### Laravel Version

10.0

### Which operating systems does with happen with?

Windows

**Comment by oriondevelops** [comment]
Hi @anastalal,

I'm sorry to hear you're running into this issue. Unfortunately, spatie/laravel-backup isn't compatible with Windows servers [as it is stated in the requirements.](https://spatie.be/docs/laravel-backup/v8/requirements#:~:text=It%27s%20not%20compatible%20with%20Windows%20servers.) This might be the primary reason for the error you're experiencing.

If you're not on a Windows server and are using [the database queue driver](https://laravel.com/docs/10.x/queues#database), it's also possible that you might have missed generating the migration. Please ensure you've done that.

Thanks for reaching out, and let me know if you have any further questions.
